### ISSUE TITLE
How to use it for audio file from remote.

### ISSUE THREAD

**Issue by kalyanpkumar** [ruebel/waveform-react#2]
When i try to give a remote url below, i receive following error -  Cannot read property 'decodeAudioData' of null... 

```
getAudioBuffer = async (path, context) => {
        console.log("get audio buffer", path);

  const response = await fetch(**remote url**);
  console.log('audio response', response);
  const audioData = await response.arrayBuffer();
  return new Promise((resolve, reject) => {
    context.decodeAudioData(audioData, buffer => {
      return resolve(buffer);
    });
  });
};
```

**Comment by ruebel** [comment]
Sounds like your context is null.  Make sure that context is a reference to the window's audio context.  Here is an example function that gets the audio context.

```javascript
export const getContext = () => {
  window.AudioContext =
    window.AudioContext ||
    window.webkitAudioContext ||
    window.mozAudioContext ||
    window.oAudioContext;
  const context = new AudioContext();
  return context;
};
```

**Comment by kalyanpkumar** [comment]
ok.. Thanks i was able to get the audio buffer... but how to play that after setting the buffer? is there anything like play() or start() to play the audio?? and how does the marker move?

**Comment by ruebel** [comment]
This library is only for displaying the waveform, displaying a position,  and allowing the user to select a position in the waveform so there are no methods to actually play the buffer.  You should use another method for playing it.

**Comment by kalyanpkumar** [comment]
ok thanks... "You should use another method for playing it." -- is it available with this plugin or you mean we need to use another plugin. if so how can we move the marker as the audio plays.

**Comment by ruebel** [comment]
You would need to use another method to play the audio.  You could use another module, or an audio tag, or the WebAudioAPI, it's up to you.  To update the marker position just update the `position` prop.

**Comment by kalyanpkumar** [comment]
ok.. thanks.. will give that a shot..
