### ISSUE TITLE
Is there any way that i can show the custom waveform

### ISSUE THREAD

**Issue by kalyanpkumar** [ruebel/waveform-react#3]
Is there any way that i can customize the waveform.. something like in the attached.
![screen shot 2017-12-01 at 8 22 36 am](https://user-images.githubusercontent.com/11042372/33465994-0d8d16dc-d671-11e7-916c-53ce3b43ec85.png)

**Comment by ruebel** [comment]
Not as of right now, but I can look into adding that.  As of right now it might be easier to fork the project if there is a specific way you need to it to draw the waveform.  I have a line drawing version close to what you show above pretty close to being ready and expect to push it up within the next week.

**Comment by ruebel** [comment]
I just pushed the 'line' plot type.  You should be able to get pretty close to that waveform style by setting plot="line" in the props.

**Comment by kalyanpkumar** [comment]
Thanks for the update... Do i need to re-install the plugin again...
